### ISSUE TITLE
'FieldInfo' object has no attribute 'required'

### ISSUE THREAD

**Issue by mechigonft** [QwenLM/CodeQwen1.5#10]
RuntimeError: Failed to import transformers.models.qwen2.modeling_qwen2 because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
'FieldInfo' object has no attribute 'required'

**Comment by mechigonft** [comment]
transformers: 4.39.3
torch：2.1.2

**Comment by cyente** [comment]
To better assist with troubleshooting the error, could you provide more detailed information that would help us replicate the issue? Specifically, it would be beneficial to know the code you executed and more description on how you use codeqwen.

**Comment by cyente** [comment]
Due to the lack of feedback for several days, we are temporarily closing this issue.

**Comment by mechigonft** [comment]
我使用transformers: 4.37.0是OK的，但是 4.39.3不行，你们说的是>=4.37.0
