### ISSUE TITLE
可否出一个Agent微调的教程

### ISSUE THREAD

**Issue by zhanpengjie** [QwenLM/CodeQwen1.5#2]
试用了code能力很不错，但是agent能力好像不高，react基本两轮就不行了，可否出一个微调教程，十分看好codeqwen系列

**Comment by cyente** [comment]
您好，CodeQwen1.5的微调可参考Qwen1.5通用模型的微调教程，[link](https://qwen.readthedocs.io/en/latest/training/SFT/llama_factory.html)

**Comment by huybery** [comment]
Thank you for your recognition of CodeQwen. We didn't include agent data during the alignment phase, so it may not be very proficient temporarily. However, we believe CodeQwen-7B is a good starting point for agent fine-tuning.
