### ISSUE TITLE
评测结果无法对齐

### ISSUE THREAD

**Issue by Soulscb** [QwenLM/CodeQwen1.5#30]
你好，我们今天对codeqwen-base模型做了humaneval的评测，发现只有33.54%的pass@1，请问这个是什么原因呢？有没有官配的评测脚本

**Comment by cyente** [comment]
https://github.com/QwenLM/CodeQwen1.5/tree/main/evaluation/eval_plus
humaneval的评测脚本在这个目录下；

请先确认一下您的评测是否正确。

**Comment by Soulscb** [comment]
你好，你们的指标没有用fim格式测试吗？

**Comment by cyente** [comment]
FIM方面的评测，我们还在整理中，目前可以先贴一下，Codeqwen1.5 humaneval-fim的评测结果
| Language | Score  |
|---|---|
| java   | 87.19% |
|py       | 75.65% |
|js       |85.07% |
