### ISSUE TITLE
当前模型是否支持中文chat问答

### ISSUE THREAD

**Issue by phvis** [QwenLM/CodeQwen1.5#34]
辛苦帮忙确认下述表述是否正确
0、如题，是否支持中文问答
1、chat模型用来做技术问答
2、base模型可以用来做inflling（代码补全）、代码注释生成（每一行生成一个注释）、代码翻译这些吗

**Comment by cyente** [comment]
0 https://huggingface.co/spaces/Qwen/CodeQwen1.5-7b-Chat-demo 支持，可以在此处尝试
1、支持
2、代码注释生成、代码翻译能力，建议采用chat模型调整prompt来实现
