### ISSUE TITLE
是否有vllm+流式推理的脚本

### ISSUE THREAD

**Issue by mechigonft** [QwenLM/CodeQwen1.5#36]
是否有vllm+流式推理的脚本

**Comment by mechigonft** [comment]
base模型，进行fim代码补全，有流式吗，只看到了chat的流式

**Comment by cyente** [comment]
和chat的流式可以一样处理

**Comment by Jacknolfskin** [comment]
如何开发自定义的流式接口呢

**Comment by mechigonft** [comment]
怎么实现vllm推理+流式输出的脚本呢？

llm = LLM(model=model_path, tensor_parallel_size=2)

outputs = llm.generate([prompt], sampling_params)

llm.generate方法的入参里面没有streamer，那怎么把创建的streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)传进去呢？

**Comment by cyente** [comment]
https://github.com/QwenLM/CodeQwen1.5/blob/main/examples/CodeQwen1.5-base.md#streaming-mode

streamer有传入的，我把chat的流式复制了一份到base模型的说明里了，请再看一下

**Comment by mechigonft** [comment]
好像还是没有解决我的问题，我想知道vllm如何实现流式推理，在qwencode模型上

**Comment by mechigonft** [comment]
vllm加速流式

**Comment by cyente** [comment]
> https://github.com/QwenLM/CodeQwen1.5/blob/main/examples/CodeQwen1.5-base.md#streaming-mode
> 
> streamer有传入的，我把chat的流式复制了一份到base模型的说明里了，请再看一下

没懂你意思，以上链接内容，就是vllm的流式推理
![image](https://github.com/QwenLM/CodeQwen1.5/assets/17844362/b5f8ad19-89bd-47d8-89bc-c50518993da7)

**Comment by mechigonft** [comment]
你好，你的意思是，你给出的这段流式的代码底层已经用上了vllm加速，我不需要显示地使用
llm = LLM(model="Qwen/CodeQwen1.5-7B")
outputs = llm.generate([prompt], sampling_params)
或者像vllm官方的https://github.com/vllm-project/vllm/blob/665c48963be11b2e5cb7209cd25f884129e5c284/vllm/entrypoints/api_server.py
脚本一样启动一个vllm的本地服务，python -m vllm.entrypoints.api_server --model /**/** --tensor-parallel-size 2 --port 8188 --host 127.0.0.1
就能用上了vllm的加速？

我的意思是，是vllm加速推理和流式返回，都需要，而你给出的代码中，没见到任何vllm的影子，这样流式的输出有vllm的加速推理效果吗？
我尝试将创建的streamer对象塞到llm.generate()方法里面，但是报错说没有这个参数

**Comment by mechigonft** [comment]
你好，你提供的TextIteratorStreamer脚本是有问题的，虽然也是流式，但是流式输出的粒度是一行代码，也就是说，模型输出时，大部分流式的结果是""，只有当一行代码生成完成后，才会在下一次流式返回的结果中将这行代码一次性输出。
![image](https://github.com/QwenLM/CodeQwen1.5/assets/90537707/abbd4327-a535-4f35-8c3f-e50863dd36d0)

![image](https://github.com/QwenLM/CodeQwen1.5/assets/90537707/37b93bc0-2b8e-4cd7-ab3f-0fa2cb80016b)
