### ISSUE TITLE
CodeQwen1.5-7b-chat代码补全测试问题

### ISSUE THREAD

**Issue by kartikzheng** [QwenLM/CodeQwen1.5#41]
测试CodeQwen1.5-7b-chat代码补全，使用的humaneval数据集，生成的java代码错乱，pass@1基本不通过。其他语言不存在这个问题。CodeQwen1.5-7b也不存在这个问题。请问各位有遇到过同样的问题吗？谢谢。

CodeQwen1.5-7b-chat生成的代码如下：
`"generation": "        Collections.sort(numbers);\n        for (int i = 0; i < numbers.size() - 1; i++) {\n            if (numbers.get(i + 1) - numbers.get(i) < threshold) {\n                return true;\n            }\n        }\n        return false;\n    }\n    public static void main(String[] args) {\n        Solution sol = new Solution();\n        System.out.println(sol.hasCloseElements(Arrays.asList(1.0, 2.0, 3.0), 0.5)); // false\n        System.out.println(sol.hasCloseElements(Arrays.asList(1.0, 2.8, 3.0, 4.0, 5.0, 2.0), 0.3)); // true\n    }\n}import java.util.*;\nimport java.lang.*;\nclass Solution {\n    /**\n    Check if in given list of numbers, are any two numbers closer to each other than given threshold.\n    >>> hasCloseElements(Arrays.asList(1.0, 2.0, 3.0), 0.5)\n    false\n    >>> hasCloseElements(Arrays.asList(1.0, 2.8, 3.0, 4.0, 5.0, 2.0), 0.3)\n    true\n     */\n    public boolean hasCloseElements(List<Double> numbers, double threshold) {\n        Collections.sort(numbers);\n        for (int i = 0; i < numbers.size() - 1; i++) {\n            if (numbers.get(i + 1) - numbers.get(i) < threshold) {\n                return true;\n            }\n        }\n        return false;\n    }\n    public static void main(String[] args) {\n        Solution sol = new Solution();\n        System.out.println(sol.hasCloseElements(Arrays.asList(1.0, 2.0, 3.0), 0.5)); // false\n        System.out.println(sol.hasCloseElements(Arrays.asList(1.0, 2.8, 3.0, 4.0, 5.0, 2.0), 0.3)); // true\n    }\n}import java.util.*;\nimport java.lang.*;\nclass Solution {\n    /**\n    Check if in given list of numbers, are any two numbers closer to each other than given threshold.\n    >>> hasCloseElements\n",`

CodeQwen1.5-7b java代码补全是正常的，如下：
`"generation": "        for (int i = 0; i < numbers.size(); i++) {\n            for (int j = i + 1; j < numbers.size(); j++) {\n                if (Math.abs(numbers.get(i) - numbers.get(j)) < threshold) {\n                    return true;\n                }\n            }\n        }\n        return false;\n    }\n    public static void main(String[] args) {\n        Solution sol = new Solution();\n        System.out.println(sol.hasCloseElements(Arrays.asList(1.0, 2.0, 3.0), 0.5));\n        System.out.println(sol.hasCloseElements(Arrays.asList(1.0, 2.8, 3.0, 4.0, 5.0, 2.0), 0.3));\n    }\n}\n",`

**Comment by cyente** [comment]
chat模型本身不是为了FIM设计的，不建议使用来做FIM。

**Comment by kartikzheng** [comment]
> chat模型本身不是为了FIM设计的，不建议使用来做FIM。

好的，多谢大佬

**Comment by ycclnn** [comment]
> chat模型本身不是为了FIM设计的，不建议使用来做FIM。
请问下，使用CodeQwen1.5-7b-AWQ + vllm0.4.0, fim对于代码似乎有一定概率返回多余的一个空格，应该怎样处理？
![image](https://github.com/QwenLM/CodeQwen1.5/assets/56081290/0ffab945-b8e5-4df0-8d49-1ded1110eabb)

**Comment by cyente** [comment]
行内生成的话，可以对于开头进行一下strip。如果是多行补全的话，建议根据上下文的缩进去double check一下格式。

**Comment by ycclnn** [comment]
> 行内生成的话，可以对于开头进行一下strip。如果是多行补全的话，建议根据上下文的缩进去double check一下格式。

你好，针对你的方案我存在疑问。例如，下图中删除掉" setupDB()"并在”await“后面触发代码补全， CodeQwen返回的completion为"  setupDB(); ........." 那么判断是否strip的逻辑会变得很复杂。
![image](https://github.com/QwenLM/CodeQwen1.5/assets/56081290/339a16c9-66bc-461e-b6d5-627f393e87ee)
更多例子：
![cc1751a1111f7453b237d89f5beb540](https://github.com/QwenLM/CodeQwen1.5/assets/56081290/8922e465-e773-4fc0-9493-00ca04839fd0)

**Comment by ycclnn** [comment]
> > 行内生成的话，可以对于开头进行一下strip。如果是多行补全的话，建议根据上下文的缩进去double check一下格式。
> 
> 你好，针对你的方案我存在疑问。例如，下图中删除掉" setupDB()"并在”await“后面触发代码补全， CodeQwen返回的completion为" setupDB(); ........." 那么判断是否strip的逻辑会变得很复杂。 ![image](https://private-user-images.githubusercontent.com/56081290/326242692-339a16c9-66bc-461e-b6d5-627f393e87ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTQ2NDUsIm5iZiI6MTcxNDI5NDM0NSwicGF0aCI6Ii81NjA4MTI5MC8zMjYyNDI2OTItMzM5YTE2YzktNjZiYy00NjFlLWI2ZDUtNjI3ZjM5M2U4N2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA4NTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZjU3NzRmNjA1YzUwZTY2MjM5ZDM5MTBkN2M0OGFiYTFiMTdiYTY5MDNlYTZkZDViZWNmZmRlYzlhYjU4ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DAfXY_8D241ZCQjju40OAeYDcExXl6Ep6owIPxOPk3g) 更多例子： ![cc1751a1111f7453b237d89f5beb540](https://private-user-images.githubusercontent.com/56081290/326243117-8922e465-e773-4fc0-9493-00ca04839fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTQ2NDUsIm5iZiI6MTcxNDI5NDM0NSwicGF0aCI6Ii81NjA4MTI5MC8zMjYyNDMxMTctODkyMmU0NjUtZTc3My00ZmMwLTk0OTMtMDBjYTA0ODM5ZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA4NTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNmIwZjAxMDA4NzJjZjllM2ZmZGU3NDVlNTgxMGRjYmE0YzE4ZTE5ZTQ2NWY5N2YyYTBiNGU1YjkxYWJiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.07DJfb--FMDQ7YRAgnlLPRsjzJLLxA2MnovvYHBNQpk)

目前来看是 sentencepiece分词导致，其他模型例如deepseek-coder-base对于补全插件放来说不需要考虑空格问题。使用起来较为简单，是否说明codeqwen-base需要补全插件开发者来单独写复杂逻辑来处理leading whitespace问题呢？
```
"decoder": {
    "type": "Sequence",
    "decoders": [
      {
        "type": "Replace",
        "pattern": {
          "String": "▁"
        },
        "content": " "
      },
      {
        "type": "ByteFallback"
      }
    ]
  },
```
