### ISSUE TITLE
How to use CodeQwen1.5 in IDEs such as vscode?

### ISSUE THREAD

**Issue by zhaoyinjiang9825** [QwenLM/CodeQwen1.5#44]

**Comment by cyente** [comment]
The basic methods of model deployment are provided with detailed tutorials in the examples section (https://github.com/QwenLM/CodeQwen1.5/tree/main/examples). Currently, we do not have the capacity to offer usage methods at a specific application level. We welcome the contribution of scripts different kinds of applications.
