### ISSUE TITLE
使用LeetCode测评集对CodeQwen1.5-7B-Base进行测评，评分为0。且一次推理，prompt传入多个问题时，输出会拼上多余的<file_sep>

### ISSUE THREAD

**Issue by aigc001** [QwenLM/CodeQwen1.5#45]
我是用README.md中推荐的方式加载CodeQwen1.5-7B-Base后，使用LeetCode测评集进行测评，评分为0。

prompt传一个问题，输出格式很正常，但是输出也未通过测试。但当一次推理传入多个问题时，会在每个问题的输出后面拼上很多个<file_sep>

请问这是什么原因？有什么可以规避的方法吗？

prompt示例：
![prompt](https://github.com/QwenLM/CodeQwen1.5/assets/162078692/ae0b82fa-c9b3-46d5-ad33-e229768915f9)

1）一次推理prompt传入单个问题的输出：
![单个问题](https://github.com/QwenLM/CodeQwen1.5/assets/162078692/aa32a151-8751-43d0-b96c-14e9408e08f9)

2）一次推理prompt传入多个问题的输出：
![多个问题](https://github.com/QwenLM/CodeQwen1.5/assets/162078692/5291b7f8-470c-4c93-9c0c-c4533a0f490c)

**Comment by cyente** [comment]
有几个点麻烦确认一下：
1、leetcode测试集，是指哪个评测脚本，如何跑的？猜测模型格式需要后处理，才能抽取出其中有效的代码内容；
2、此类问题，建议您采用chat模型进行测试；
3、不理解您说的“一次推理传入多个问题”是什么意思？
4、麻烦给可复现的脚本

**Comment by aigc001** [comment]
> 有几个点麻烦确认一下： 1、leetcode测试集，是指哪个评测脚本，如何跑的？猜测模型格式需要后处理，才能抽取出其中有效的代码内容； 2、此类问题，建议您采用chat模型进行测试； 3、不理解您说的“一次推理传入多个问题”是什么意思？ 4、麻烦给可复现的脚本

感谢您在百忙之中抽出时间答复。针对您提出的问题，以下是我的回应：

1-->测评脚本使用的时https://github.com/deepseek-ai/DeepSeek-Coder/tree/main/Evaluation/LeetCode中的vllm_inference.py，对里面的模型加载和调用generate()做了适配修改。执行方式详见同目录下的README

2-->因分析需要，需要对base与chat模型都进行评估

3-->多个问题指的是如下示例：
input_text = ["question1", "question2"]
model_inputs = TOKENIZER(input_text, return_tensors="pt").to(device)

4-->因适配修改后的脚本在内网，因it审计不方便对外提供。

**Comment by cyente** [comment]
> > 有几个点麻烦确认一下： 1、leetcode测试集，是指哪个评测脚本，如何跑的？猜测模型格式需要后处理，才能抽取出其中有效的代码内容； 2、此类问题，建议您采用chat模型进行测试； 3、不理解您说的“一次推理传入多个问题”是什么意思？ 4、麻烦给可复现的脚本
> 
> 感谢您在百忙之中抽出时间答复。针对您提出的问题，以下是我的回应：
> 
> 1-->测评脚本使用的时[https://github.com/deepseek-ai/DeepSeek-Coder/tree/main/Evaluation/LeetCode中的vllm_inference.py，对里面的模型加载和调用generate()做了适配修改。执行方式详见同目录下的README](https://github.com/deepseek-ai/DeepSeek-Coder/tree/main/Evaluation/LeetCode%E4%B8%AD%E7%9A%84vllm_inference.py%EF%BC%8C%E5%AF%B9%E9%87%8C%E9%9D%A2%E7%9A%84%E6%A8%A1%E5%9E%8B%E5%8A%A0%E8%BD%BD%E5%92%8C%E8%B0%83%E7%94%A8generate()%E5%81%9A%E4%BA%86%E9%80%82%E9%85%8D%E4%BF%AE%E6%94%B9%E3%80%82%E6%89%A7%E8%A1%8C%E6%96%B9%E5%BC%8F%E8%AF%A6%E8%A7%81%E5%90%8C%E7%9B%AE%E5%BD%95%E4%B8%8B%E7%9A%84README)
> 
> 2-->因分析需要，需要对base与chat模型都进行评估
> 
> 3-->多个问题指的是如下示例： input_text = ["question1", "question2"] model_inputs = TOKENIZER(input_text, return_tensors="pt").to(device)
> 
> 4-->因适配修改后的脚本在内网，因it审计不方便对外提供。

不可复现的问题，我们无法讨论。。。

看起来你说的，"多个问题"像在做batch inference。需要自己对末尾tokens进行strip，CodeQwen的specialtokens为： "<fim_prefix>"  "<fim_middle>" "<fim_suffix>" "<fim_pad>" "<repo_name>" "<file_sep>" '<|im_start|>' '<|im_end|>' "<|endoftext|>"

**Comment by mechigonft** [comment]
fim_pad标签的作用是什么？

**Comment by cyente** [comment]
训练细节请等我们技术报告

**Comment by mechigonft** [comment]
@cyente 你好，请问下fim_pad标签的作用是什么？

**Comment by cyente** [comment]
> @cyente 你好，请问下fim_pad标签的作用是什么？

训练需要，与inference无关
