### ISSUE TITLE
AWQ版本的首字推理效率要比非量化版本低是什么原因

### ISSUE THREAD

**Issue by feather820** [QwenLM/CodeQwen1.5#46]
AWQ版本的首字推理效率要比非量化版本低很多，大概是3倍左右的样子，推理脚本参考的huggingface上的示例。请问对AWQ版本的模型是有什么其他的推理方式吗，不能用transformers直接推理

**Comment by cyente** [comment]
https://github.com/QwenLM/CodeQwen1.5/blob/main/examples/CodeQwen1.5-base.md#use-codeqwen15-base-by-vllm

建议采用vllm加速推理，是否效果还有差异？

**Comment by feather820** [comment]
使用awq的vllm的版本是什么？我这边测试的vllm对awq的加速比不过没有经过量化的
