### ISSUE TITLE
跨文件补全

### ISSUE THREAD

**Issue by mechigonft** [QwenLM/CodeQwen1.5#49]
在跨文件补全时，使用file_sep引入相关文件信息时，哪些代码是可以省略的？ 从而压缩prompt token的长度，传入更多的相关文件信息

我觉得模型在调用某个bean的某个方法时，不需要知道该方法的代码实现，只需要根据接口功能描述（方法注释）、出入参、方法名即可判断是否该引用这个方法，因此我在构造file_sep时尝试将方法的方法体/方法实现删掉，只保留方法定义，让模型推理，结果是模型推理结果不可用，模型推理开始尝试去补全这些接口的代码，请问这个问题你们有研究过吗？

**Comment by mechigonft** [comment]
能不能把一些依赖文件压缩成像接口一样，只给接口定义，不给接口实现

**Comment by cyente** [comment]
尚未有明确结论，欢迎您的探索以及结论
