### ISSUE TITLE
Question about training datasets

### ISSUE THREAD

**Issue by Owen-Qin** [QwenLM/CodeQwen1.5#56]
Hi Qwen team,

Thanks for your great work! I just have two quick questions.
1. Does the pretaining dataset contain the new released stack v2?
2. Could you shed some light on the creation of the SFT dataset? For example, did you use synthesis data? What is the magnitude of the SFT data?

Will there be a technical paper for CodeQwen?

**Comment by cyente** [comment]
Thank you for your appreciation. We didn't use stack v2; instead, we built our own training set. Please wait for our technical report for more details about our training.
