### ISSUE TITLE
请问是否可以提供CodeQwen1.5在TextToSql性能上的评测脚本？

### ISSUE THREAD

**Issue by IeohMingChan** [QwenLM/CodeQwen1.5#63]
请问是否可以提供CodeQwen1.5在TextToSql性能上的评测脚本？在README里给出了TextToSql评估结果，但是并没有对应的代码开源，而其他评估项目的代码均已开源

**Comment by cyente** [comment]
https://github.com/QwenLM/CodeQwen1.5/tree/main/evaluation/text_to_sql
此处提供了，我们进行Text2sql的对应评测集进行评测的prompt格式。

具体评测脚本尚在整理当中
