### ISSUE TITLE
测试下来准确性很高，但是个别关键字会有错误

### ISSUE THREAD

**Issue by njalan** [QwenLM/CodeQwen1.5#64]
目前遇到最明显的问题就是当在提问中提到'夜班'或者'晚班'生成的sql基本都是错的，我在ddl 列的comments 已经添加了comments 比如 '晚班'='night shift'. 其他列添加同样的comments 唯独'夜班'或者'晚班'会有问题。

**Comment by cyente** [comment]
谢谢您的反馈，此类问题，可能需要通过一些规则后处理解决。

**Comment by njalan** [comment]
@cyente 大佬如何通过规则解决？ 请问下个版本什么时候发布？

**Comment by cyente** [comment]
就是针对您发现容易出现错误的内容，进行后处理。下个版本模型尚在开发中。。
