### ISSUE TITLE
codeqwen对鸿蒙代码生成的支持？

### ISSUE THREAD

**Issue by yz-1130** [QwenLM/CodeQwen1.5#69]
codeqwen有针对鸿蒙开发语言arkUI和arkTS的支持计划吗？目前codeqwen1.5-7b生成的鸿蒙代码不如glm4，这个场景基本基本无法使用

**Comment by cyente** [comment]
您好，感谢您的意见，我们会尽快做出反馈。是否方便提供1～2个例子（包括，您尝试的模型输入，以及期望的输出结果），帮助我们判断一下，目前codeqwen模型对于arkTS的支持情况？

**Comment by yz-1130** [comment]
目前，我使用下来，codeqwen对arkTS的代码生成能力不如glm4.
如帮我创建一个：网格布局的harmony代码，codeQwen并不能很好的理解和生成。
期待对鸿蒙代码的生成理解能力能达到java的水平

**Comment by cyente** [comment]
谢谢您的反馈

**Comment by yz-1130** [comment]
如：跳转拨号界面示例代码
实际输出：

期望输出：
`// import需要的模块
import call from '@ohos.telephony.call';
import observer from '@ohos.telephony.observer';

// 调用查询能力接口
let isSupport = call.hasVoiceCapability();
if (!isSupport) {
    console.log("not support voice capability, return.");
    return;
}
// 如果设备支持呼叫能力，则继续跳转到拨号界面，并显示拨号的号码
call.makeCall("13xxxx", (err)=> {
    if (!err) {
        console.log("make call success.");
    } else {
        console.log("make call fail, err is:" + JSON.stringify(err));
    }
});
// 订阅通话业务状态变化（可选）
observer.on("callStateChange", (data) => {
    console.log("call state change, data is:" + JSON.stringify(data));
});`

**Comment by yz-1130** [comment]
实际输出：kotlin语言
![image](https://github.com/QwenLM/CodeQwen1.5/assets/24471727/e6b8cd9c-dd8a-420f-981f-6d9f7950b36d)
