### ISSUE TITLE
about code completions 

### ISSUE THREAD

**Issue by who52023** [QwenLM/CodeQwen1.5#71]
prompt = '<fim_prefix>' + prefix_code + '<fim_suffix>' + suffix_code + '<fim_middle>'
使用此方法在行间补全时不是很准确，（比如函数中间确实几行），请问需要如何使用fim标签在这种情况下能准确补全。
另外看到有<fim_pad>标签，有什么特别的使用方式吗？

**Comment by cyente** [comment]
`<fim_pad>` is only a placeholder tokens during training. 

https://github.com/QwenLM/CodeQwen1.5/blob/main/examples/CodeQwen1.5-base.md please check out this document for FIM.
