### ISSUE TITLE
模型对repository level级别的续写支持引入多个不同的<repo_name>吗？

### ISSUE THREAD

**Issue by Lanyu123** [QwenLM/CodeQwen1.5#73]
codeqwen模型对repository level的续写支持引入多个不同的<repo_name>吗？ 我的理解是<repo_name>后跟的应该是包名，对吗？
望解答~

**Comment by cyente** [comment]
We have not yet verified the effectiveness in a 'multi-repo' scenario. You can try this format, or treat the module as a file within a file directory.
