### ISSUE TITLE
FIM的训练数据格式

### ISSUE THREAD

**Issue by mechigonft** [QwenLM/CodeQwen1.5#80]
codeQwen是非常伟大的工作，感谢开发团队的付出！
想要对Base模型的FIM推理方式进行微调，微调训练的数据格式是怎么样的？输入是类似于推理阶段的fim标签的拼接吗？输出是期望生成的代码段内容？

**Comment by cyente** [comment]
是的，您可以使用类似于推理阶段的fim标签的拼接。比较简单有效的方法，我们建议，先不要拼接任何chat format格式，直接将plain text作为输入。

**Comment by mechigonft** [comment]
感谢回复，我想进一步了解下：你指的“先不要拼接任何chat format格式”是指的llama Factory上面的template字段，训练模板吗？如果是base模型，我好像可以直接指定template为default吧？
![image](https://github.com/QwenLM/CodeQwen1.5/assets/90537707/c9a29d6c-83ac-4ce6-9c33-be9088e32e99)

**Comment by mechigonft** [comment]
![image](https://github.com/QwenLM/CodeQwen1.5/assets/90537707/aed5eb9c-969b-4a37-ac66-e1bca7212cc4)
default的训练模板好像并不太对，因为会加上Human、Assistant等信息

**Comment by cyente** [comment]
是的建议，先不要增加这些模版，可能会降低训练难度。更丰富的训练策略，我们正在探索中
