### ISSUE TITLE
如何同时实现单行和多行代码补全？

### ISSUE THREAD

**Issue by zhengshengh** [QwenLM/CodeQwen1.5#87]
you can limit the tokens of \n or " \n" during generation, and add the '\n' at the suffix part

_Originally posted by @cyente in https://github.com/QwenLM/CodeQwen1.5/issues/86#issuecomment-2308907667_
        
你好，请问有没有更加智能的做法？
根据上述方案，如果每次都通过判断尾部的"\n"来实现，那不是等于抛弃了多行补全么？

**Comment by cyente** [comment]
https://github.com/QwenLM/CodeQwen1.5/blob/main/examples/CodeQwen1.5-base-fim.py

use these kind of format， you could let the model to choose whether infilling single or multi-line.

**Comment by hcbr** [comment]
> https://github.com/QwenLM/CodeQwen1.5/blob/main/examples/CodeQwen1.5-base-fim.py
> 
> use these kind of format， you could let the model to choose whether infilling single or multi-line.

I cannot find this file  https://github.com/QwenLM/CodeQwen1.5/blob/main/examples/CodeQwen1.5-base-fim.py

**Comment by zql365747776** [comment]
@cyente 2.5 有没有新的文档？ 或者有没有什么方案能控制单行或者多行补全？ 
感谢！
